baseURL: "https://bojan93.github.io/my-blog/"
relativeURLs: true
languageCode: en-us
title: 📚 Learning Corner
theme: "PaperMod"
params:
    homeInfoParams:
        Title: Hi there 👋
        Content: Welcome to my blog where I'll cover various topics around programming