baseURL: https://bojan93.github.io/my-blog/
languageCode: en-us
title: 📚 Learning Corner
theme: "PaperMod"
params:
    homeInfoParams:
        Title: Hi there 👋
        Content: Welcome to my blog (to be updated)